### ISSUE TITLE
Multi-locks

### ISSUE THREAD

**Issue by japaric** [rtfm-rs/cortex-m-rtfm#104]
AKA locking several resources at once.

Mock API:

``` rust
(resources.A, resources.B).lock(|a: &mut u32, b: &mut i32| { .. })
// repeat for tuples of other sizes
```

Benefits compared to

``` rust
resources.A.lock(|a| {
    resources.B.lock(|b| {
        // ..
    });
});
```

- Less rightward drift
- Only a single critical section is created
- All resources are *atomically* locked (locked "at the same time")

Requirements:

- This should not complicate generic code. So no more user facing traits should be added.

- Also, ideally, this should Just Work:

``` rust
fn foo(a: impl Mutex<T = u32>, b: impl Mutex<T = i32>) {
    a.lock(|a| {});
    b.lock(|b| {});
    (a, b).lock(|a, b| ..)
}
```

**Comment by arkap** [comment]
I was just going to open an issue on this topic, because when I try to acquire multiple locks like in your example:

> ```
> resources.A.lock(|a| {
>    resources.B.lock(|b| {
>        // ..
>    });
> });


the borrow-checker complains about multiple mutable borrows of `resources`.
So yeah, I would love to see a possibility to lock multiple resources atomically.

**Comment by TeXitoi** [comment]
Maybe this is working:
```rust
let b = &mut resources.B
resources.A.lock(|a| {
   b.lock(|b| {
       // ..
   });
});
```

**Comment by TeXitoi** [comment]
@arkap https://stackoverflow.com/questions/36379242/mutably-borrow-one-struct-field-while-borrowing-another-in-a-closure

**Comment by arkap** [comment]
Yes, that did the trick. Thank you!
I would still love to see an explicit API for this, though. Makes for more readable code.

**Comment by TotalKrill** [comment]
Yes, this is an annoyance when using RTFM, The rightward drift is hard to read and reason about, and doesn't give much benefit. Would love to see this work

**Comment by korken89** [comment]
This feature comes with [`mutex-trait`](https://github.com/rust-embedded/mutex-trait) from the embedded WG. Closing

**Comment by little-arhat** [comment]
@korken89 any examples or docs on how to integrate it with RTFM? Does RTFM analysis "knows" about this mutex trait?
