### ISSUE TITLE
ARMv6: use interrupt masking instead of "global" critical sections

### ISSUE THREAD

**Issue by japaric** [rtfm-rs/cortex-m-rtfm#105]
Right now `Mutex.lock` is disabling *all* interrupts when compiled for ARMv6-M because there's no BASEPRI on that sub-architecture.

We can do better by disabling only *some* interrupts using the NVIC_ICER when entering the critical section and re-enabling them using the NVIC_ISER on exit. To do that we need to compute the mask that will disable the right interrupts.

ICER and ISER are both 32-bit registers that only allow word access. The critical section would look like this (pseudo-code):

``` rust
fn lock<R>(f: impl FnOnce(&mut T) -> R) -> R {
    // disable some interrupts
    NVIC_ICER = MASK; // NOTE volatile write
    let val = f();
     // re-enable them
    NVIC_ISER = MASK; // NOTE volatile write
    val
}
```

where `MASK` is computed like this:

``` rust
// Interruptx are the interrupts that need to be disabled
const MASK: u32 = Interrupt1.nr() | Interrupt2.nr() | InterruptN.nr();
```

The ceiling analysis would need to be updated to track the names the tasks (interrupts) that may access the resource apart from their priorities.

UPDATE: above I ignored exceptions. Those would need to be masked too. Different registers are used to mask core exceptions.

**Comment by korken89** [comment]
This should be moved into an RFC, can you fix one @japaric ?

**Comment by japaric** [comment]
I believe @perlindgren and / or @nils-grepit have been working on this. They can probably submit a RFC / PR.

One unresolved question that I didn't mention in the issue description is: what is the expected behavior of the user masking an interrupt within a `lock` closure that also masks that interrupt? See code below:

``` rust
#[task(binds = A, resources = [x], priority = 1)]
fn foo(cx: foo::Context) {
    cx.x.lock(|_| { // interrupt B masked
        NVIC::mask(Interrupt::B);
    }); // interrupt B unmasked
    // interrupt B is unmasked at this point but that's probably NOT what the user wanted
}

#[task(binds = B, resources = [x], priority = 2)]
fn bar(cx: bar::Context) {
    // ..
}
```

**Comment by japaric** [comment]
This issue is not actionable without a RFC that answers the above question and gives more details about how the masking will be done so I'm going to close this in favor of a proper RFC, or just a thread to start, in rtfm-rs/rfcs
