### ISSUE TITLE
Share `core.SCB` with interrupts?

### ISSUE THREAD

**Issue by azasypkin** [rtfm-rs/cortex-m-rtfm#165]
Hey,

I tried to migrate to `rtfm` the other day and the only issue that I couldn't solve is sharing `core.SCB` with interrupts. If I'm not mistaken only `init` has access to mutable reference to `core.SCB` and that's it. 

My device is supposed to process USB/RTC interrupts and as a result it may want to toggle deep sleep mode (`SCB.scr` register) or do a soft reset (`SCB.aircr` register).

Am I missing something or there is no way currently to achieve that with RTFM?

**Comment by hdhoang** [comment]
we have the same need for soft reset, and have made rust-embedded/cortex-m#138 to trigger it without having an instance of SCB. It's safe because it is one write, I don't know if deep sleep works similarly. I hope we can find a satisfactory solution.

**Comment by azasypkin** [comment]
Ah, interesting, thanks for sharing @hdhoang! Yeah, I think same could work for [deep sleep](https://docs.rs/cortex-m/0.6.0/src/cortex_m/peripheral/scb.rs.html#585-589). In case we don't have other choice and your PR gets accepted I'll prepare the same for deep sleep.

**Comment by hdhoang** [comment]
hi @azasypkin, you can start preparing a similar PR for deepsleep now, to enter the same deprecation cycle (0.6.1 to 0.7).

**Comment by azasypkin** [comment]
Yep, thanks for the ping @hdhoang! Created PR: https://github.com/rust-embedded/cortex-m/pull/145

**Comment by japaric** [comment]
This can be done in v0.5.x (not yet released but you can try master)
