### ISSUE TITLE
Details of context switch implementation

### ISSUE THREAD

**Issue by kanishkarj** [rtfm-rs/cortex-m-rtfm#228]
Hey !
I am a computer science undergrad, as a part of my undergraduate thesis, I am working on a realtime kernel in rust. while implementing context switch, I wrote the code in assembly which switches between tasks. But I am not sure if that is such a safe implementation, so I tried to look into how cortex-m-rftm implemented a context switch, but I haven't been able to figure it out how it was implemented. Could someone throw some light on that ?

**Comment by TeXitoi** [comment]
There is no software context switches, only hardware interruptions.

**Comment by korken89** [comment]
I have a presentation of the C++ version here that explains the underlying workings (it's the same in the Rust version) that might be of help: https://youtu.be/SBij9W9GfBw

**Comment by kanishkarj** [comment]
@TeXitoi Oh, that makes sense.

Thanks @TeXitoi @korken89

**Comment by korken89** [comment]
This discussion seems done.
