### ISSUE TITLE
Syntax for a static resource that changes type

### ISSUE THREAD

**Issue by lthiery** [rtfm-rs/cortex-m-rtfm#232]
I have a pin that is normally an input, but is repurposed as an output during a certain event. Since input/output are different types, I need to move the pin, use it in its different state, and then put it back.

I am stuck though as an RTFM managed resource is either `mut &` or `&` as far as I can tell. 
[And so my solution looks like this.](https://github.com/lthiery/stm32l0xx-hal/blob/dynamic-pin-type/examples/dynamic_pin.rs).

Is there a nicer way of doing this that I missed?

**Comment by TeXitoi** [comment]
You can have the `Option<Pin>` as a ressource, and access it mutably using the lock API.

**Comment by little-arhat** [comment]
Similar issue arises when using DMA in rtfm applications. We model this, indeed, using Option<WrapperType>, where wrapper is something like `struct { Busy(..), Ready(..)}`. It's possible then to use Option::take and update resources, like this: https://github.com/copterust/proving-ground/blob/master/dma_int/main.rs#L126.
