### ISSUE TITLE
No site available on https://rtfm.rs/

### ISSUE THREAD

**Issue by no111u3** [rtfm-rs/cortex-m-rtfm#262]
I cannot open https://rtfm.rs/ - GitHub return 404: There isn't a GitHub Pages site here.
So I cannot open previous saved link on another parts of site (manual for 0.5 and 0.4 crate version)

**Comment by japaric** [comment]
Thanks for the report. This should be fixed now (may need to wait a few minutes for GH to updates this repo GH pages).

@korken89 merging PRs into the v0.4.x branch triggers CI builds that build docs and push those old docs into the gh-pages branch; that causes the rtfm.rs docs to be overridden with an old version. We need to update the build script of the v0.4.x branch to *not* push to the gh-pages branch.
