### ISSUE TITLE
No API available for 0.4

### ISSUE THREAD

**Issue by no111u3** [rtfm-rs/cortex-m-rtfm#264]
For first page (Preface - https://rtfm.rs/0.4/book/en/) we have the link of crate API - https://rtfm.rs/0.4/book/api/rtfm/index.html
For version 0.5 crate API available, but for 0.4 not available.

**Comment by japaric** [comment]
the relative link used in the book is wrong; PR #265 should fix it

**Comment by korken89** [comment]
This is now fixed. Closing
